<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWhHXxkA\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWhHXxkA/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWhHXxkA.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWhHXxkA\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWhHXxkA\App_KernelProdContainer([
    'container.build_hash' => 'WhHXxkA',
    'container.build_id' => 'a84bfa9e',
    'container.build_time' => 1579302852,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWhHXxkA');
