<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_user_number' => [[], ['_controller' => 'App\\Controller\\UserController::number'], [], [['text', '/user/number']], [], []],
    'app_user_register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/user/register']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
