#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_user_number:
    path: /user/number
    controller: App\Controller\UserController::number
    methods: POST


app_post_create:
    path: /post/create
    controller: App\Controller\PostController::create
    methods: POST

app_post_update:
    path: /post/update/{id}
    controller: App\Controller\PostController::update
    methods: PUT

app_post_delete:
    path: /post/delete/{id}
    controller: App\Controller\PostController::delete
    methods: GET

app_post_list:
    path: /post/list
    controller: App\Controller\PostController::list
    methods: GET    

app_likes_create:
    path: /likes/create
    controller: App\Controller\LikesController::create
    methods: POST


app_comments_create:
    path: /comments/create
    controller: App\Controller\CommentsController::create
    methods: POST

# app_user_register:
#     path: /register
#     controller: App\Controller\UserController::register
#     methods:    POST|HEAD    

# app_user_register:
#     path:  /user/register
#     controller: App\Controller\UserController::register
#     methods: POST
    

# api_login_check:
#     path: /api/login_check
#     methods: POST      

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::getTokenUser

test:
  path: /api/test
  controller: App\Controller\ApiController::test