<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEd1NkBk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEd1NkBk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEd1NkBk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEd1NkBk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEd1NkBk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ed1NkBk',
    'container.build_id' => '8e3c0273',
    'container.build_time' => 1579545012,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEd1NkBk');
