<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXY771Hx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXY771Hx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXY771Hx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXY771Hx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXY771Hx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XY771Hx',
    'container.build_id' => 'b5ca6e54',
    'container.build_time' => 1579473742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXY771Hx');
