<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xxRFHG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xxRFHG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5xxRFHG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5xxRFHG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5xxRFHG\App_KernelDevDebugContainer([
    'container.build_hash' => '5xxRFHG',
    'container.build_id' => '2fc1e647',
    'container.build_time' => 1579283581,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xxRFHG');
